version: "3"
services:
  mysql:
    image: mysql:8.0.28
    restart: always
    container_name: YOUR_PROJECT-db
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      ecshub_net:
        ipv4_address: 172.18.0.2

  phpmyadmin:
    image: phpmyadmin:5.1.1-apache
    restart: always
    container_name: YOUR_PROJECT-phpmyadmin
    links:
      - mysql
    depends_on:
      - mysql
    env_file: .env
    environment:
      MYSQL_USERNAME: ${DATABASE_ROOT_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      PMA_HOST: mysql
    ports:
      - 8083:80
    networks:
      ecshub_net:
        ipv4_address: 172.18.0.3

  php:
    build: ./php/
    image: php:8-fpm
    restart: always
    container_name: YOUR_PROJECT-php
    links:
      - mysql
    depends_on:
      - mysql
    volumes:
      - ./php/:/usr/local/etc/php/
      - ./www/:/var/www/html
    ports:
      - 9000:9000
    networks:
      ecshub_net:
        ipv4_address: 172.18.0.4

  nginx:
    build: ./nginx/
    image: nginx:1.21
    restart: always
    container_name: YOUR_PROJECT-web
    links:
      - php
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - "./nginx:/etc/nginx/conf.d"
      - "./www/:/var/www/html"
    networks:
      ecshub_net:
        ipv4_address: 172.18.0.5

networks:
  ecshub_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
